services:
  task-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
      - auth-service
    environment:
      - 'AUTH_SERVICE_URL=http://auth-service:8083'
      - 'FILE_SERVICE_URL=http://file-service:8084'

  auth-service:
    build:
      context: ../auth-service
      dockerfile: ../auth-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redis

  file-service:
    build:
      context: ../file-service
      dockerfile: ../file-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - redis
      - auth-service
    environment:
      - 'TASK_SERVICE_URL=http://task-service:8082'
      - 'AUTH_SERVICE_URL=http://auth-service:8083'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5425:5432'
    expose:
      - '5425'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
